autopecas/autopecas/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from core.views import index, contact

urlpatterns = [
    path('', index, name='index'),
    path('items/', include('item.urls')),
    path('contact', contact, name='contact'),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

autopecas/item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('<int:pk>/', views.detail, name='detail'),
]

autopecas/core/models.py
from django.db import models

# Create your models here.

autopecas/item/models.py
from django.db import models

class category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categorias'

    def __str__(self):
        return self.name
    
class Item(models.Model):
    category = models.ForeignKey(category, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    Descrição = models.TextField(blank=True, null=True)
    Preço = models.FloatField()
    image = models.ImageField(upload_to='item_images', blank=True, null=True)
    foi_vendido = models.BooleanField(default=False)

    def __str__(self):
        return self.name

autopecas/core/views.py
from django.shortcuts import render

from item.models import category, Item

def index(request):
    items = Item.objects.filter(foi_vendido=False) [0:6]
    categorias = category.objects.all()

    return render(request, 'core/index.html', {
        'categorias': categorias,
        'items': items,
    })

def contact(request):
    return render(request, 'core/contact.html')

autopecas/item/views.py
from django.shortcuts import render, get_object_or_404
from django.db.models import Q

from .models import category,Item

def items(request):
    query = request.GET.get('query', '')
    category_id = request.GET.get('category',0)
    categorias = category.objects.all()
    items = Item.objects.filter(foi_vendido = False)

    if category_id:
        items = items.filter(category_id=category_id)

    if query:
        items = items.filter(Q(name__icontains = query) | Q(Descrição__icontains = query))

    return render(request, 'item/items.html', {
        'items': items,
        'query': query,
        'categorias': categorias,
        'category_id': int(category_id),
    })

def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    related_items = Item.objects.filter(category = item.category, foi_vendido = False).exclude(pk=pk)[0:3]

    return render(request, 'item/detail.html', {
        'item': item,
        'related_items': related_items
    })


autopecas/core/templates/core/base.html
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <script src="https://cdn.tailwindcss.com"></script>

        <title>{% block title %}{% endblock %} Charlo AutoPeças</title>
    </head>

    <body>
        <nav class="py-6 px-6 flex justify-between items-center border-b border-grey-200">
            <a href="/" class="text-xl font-semibold">Charlo AutoPeças</a>

            <div class="space-x-6">
                <a href="{% url 'item:items' %}" class="text-lg font-semibold hover:text-gray-500">Produtos</a>
            </div>
        </nav>
        <div class="px-6 py-6">
            {% block content %}
            {% endblock %}
        </div>

        <footer class="py-6 px-6 flex justify-between bg-gray-800">
            <div class="w-2/3 pr-10">
                <h3 class="mb-5 font-semibold text-gray-400">Sobre</h3>

                <p class="text-lg text-gray-300">Esse site é voltado para os amantes automobilisticos, aqui voce encontrara
                    as mais variadas pecas, para qualquer que seja o seu automovel !!!
                </p>

                <p class="text-lg text-gray-300">Feito Por: Gabriel.C</p>
            </div>

            <div class="w-1/3">
                <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>

                <ul class="space-y-2">
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Sobre</a></li>
                    <li><a href="{% url 'contact' %}" class="text-lg text-teal-500 hover:text-teal-700">Contato</a></li>
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Politicas de Privacidade</a></li>
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Termos de Uso</a></li>
                </ul>
            </div>
        </footer>
    </body>
</html>

autopecas/core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block content %}
    <h1>Pagina de Contato</h1>
{% endblock %}

autopecas/core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Bem Vindo{% endblock %}

{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Novos Itens</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for item in items %}
                <div>
                    <a href="{% url 'item:detail' item.id %}">
                        <div>
                            <img src="{{item.image.url}}" height="50%" width="100%" class="rounded-t-xl">
                        </div>

                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{item.name}}</h2>
                            <p class="text-gray-500">Preço: R$ {{item.Preço}}</p>
                        </div>
                    </a>
                    
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Categorias</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for Category in categorias %}
            <div>
                <a href="#">
                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{Category.name}}</h2>
                        
                    </div>
                </a>
                
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

autopecas/item/templates/item/detail.html
{% extends 'core/base.html' %}

{% block title %}{{ item.name }}{% endblock %}

{% block content %}
<div class="grid grid-cols-5 gap-6">
 <div class="col-span-3">
    <img src="{{ item.image.url }}" class="rounded-xl">
 </div>

 <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">{{ item.name }}</h1>
    <p class="text-gray-500"><strong>Preço: R$ </strong> {{item.Preço}} </p>

    {% if item.Descrição %}
    <p class="text-gray-700">
        <strong class="text-gray-500">Descrição:</strong><br>
        {{item.Descrição}}
    </p>
    {% endif %}

    <a href="#" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover: bg-teal-700">Comprar</a>

 </div>
</div>

<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Itens Relacionados</h2>

    <div class="grid grid-cols-3 gap-3">
        {% for item in related_items %}
            <div>
                <a href="{% url 'item:detail' item.id %}">
                    <div>
                        <img src="{{item.image.url}}" class="rounded-t-xl">
                    </div>

                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{item.name}}</h2>
                        <p class="text-gray-500">Preço: R$ {{item.Preço}}</p>
                    </div>
                </a>
                
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

autopecas/item/templates/item/items.html
{% extends 'core/base.html' %}

{% block title %}Items{% endblock %}

{% block content %}
    <div class="pb-6 grid grid-cols-4 gap-4 bg-gray-100">
        <div class="col-span-1">
            <form method="get" action="{% url 'item:items' %}">
                <input name="query" class="w-full py-4 px-6 border rounded-xl" type="text" value="{{ query }}" placeholder="Ache uma bike, uma cadeira ou carro...">

                <button class="mt-2 py-6 px-8 text-lg bg-teal-500 text-white rounded-xl">Busca</button>
            </form>

            <hr class="mt-6">

            <p class="font-semibold">Categorias</p>

            <ul>
                {% for category in categorias %}
                    <li class="py-2 px-2 rounded-xl{% if category.id == category_id %} bg-gray-200{% endif %}">
                        <a href="{% url 'item:items' %}?query={{ query }}&category={{ category.id }}"> {{ category.name }}</a>
                    </li>
                {% endfor %}
            </ul>

            <hr class="my-6">

            <p class="font-semibold">Limpar Filtros</p>

            <ul>
                <li><a href="{% url 'item:items' %}" class="mt-2 py-4 px-8 inline-block bg-yellow-500 text-lg rounded-xl text-white">Limpar </a></li>
            </ul>
        </div>
        <div class="col-span-3">
            <div class="grid grid-cols-3 gap-3">
                {% for item in items %}
                    <div>
                        <a href="{% url 'item:detail' item.id %}">
                            <div>
                                <img src="{{item.image.url}}" height="50%" width="100%" class="rounded-t-xl">
                            </div>
    
                            <div class="p-6 bg-white rounded-b-xl">
                                <h2 class="text-2xl">{{item.name}}</h2>
                                <p class="text-gray-500">Preço: R$ {{item.Preço}}</p>
                            </div>
                        </a>
                        
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}